<a href="https://colab.research.google.com/github/shivamanisuram/VECTOR-OPERATIONS-IN-ML/blob/main/MATRIX_OPERATIONS_PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

creating matrix using array

In [3]:
matrix_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
matrix_1.shape

(3, 3)

creating matrix with random values

In [7]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.90193798 0.15259454 0.49619749]
 [0.34586572 0.62371965 0.05180508]
 [0.19904454 0.17136522 0.70023508]]


In [12]:
#creating random matrix with random integers
random_integer_matrix=np.random.randint(100,size=(4,5))
print(random_integer_matrix)

[[62 59 60  9  9]
 [77 86 96 76 73]
 [50 76 43 97 69]
 [69 87 39 21 72]]


matrix with all values as 1

In [14]:
matrix_3=np.ones((3,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
matrix_3=np.ones((3,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
null_matrix=np.zeros((3,3))
print(null_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
identity_matrix=np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
#transpose of a matrix
a=np.random.randint(100,size=(4,5))
print(a)

[[75 25 69  3 95]
 [30 73 76 89 42]
 [25 21 47 39 84]
 [59  0 82 54 25]]


In [21]:
transpose_of_a=np.transpose(a)
print(transpose_of_a)

[[75 30 25 59]
 [25 73 21  0]
 [69 76 47 82]
 [ 3 89 39 54]
 [95 42 84 25]]


In [22]:
#MATRIX ADDITION
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
c=a+b
print(c)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [23]:
a.shape

(3, 3)

In [24]:
b.shape

(3, 3)

In [25]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [28]:
#create two matrcies with random values
a=np.random.randint(100,size=(4,5))
b=np.random.randint(100,size=(4,5))
print(a)
print(b)

[[75 14 42 11 82]
 [37 14 39 25 42]
 [76 71 70 84 25]
 [63  8 49 45 73]]
[[33 29 62 68  3]
 [95 78 89 85 80]
 [99 79 64 26 97]
 [91  2 58 56 63]]


In [29]:
sum=a+b
print(sum)

[[108  43 104  79  85]
 [132  92 128 110 122]
 [175 150 134 110 122]
 [154  10 107 101 136]]


In [30]:
sum=np.add(a,b)
print(sum)

[[108  43 104  79  85]
 [132  92 128 110 122]
 [175 150 134 110 122]
 [154  10 107 101 136]]


matrix subtraction

In [31]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])



In [32]:
print(A)

[[2 3]
 [4 5]]


In [33]:
print(B)

[[6 7]
 [8 9]]


In [35]:
difference=A-B
print(difference)

[[-4 -4]
 [-4 -4]]


In [36]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [37]:
print(matrix_1)
print(matrix_2)



[[6 5 5]
 [2 1 3]
 [7 4 6]]
[[ 7  6  5]
 [10  5 13]
 [ 7  6  8]]


In [38]:
diff = np.subtract(matrix_1, matrix_2)


In [39]:

print(diff)



[[ -1  -1   0]
 [ -8  -4 -10]
 [  0  -2  -2]]


In [40]:

#MULTIPLYING A MATRIX BY SCALAR
x=5
y=np.random.randint(10,size=(3,3))
print(y)

[[9 1 4]
 [8 4 7]
 [5 8 8]]


In [42]:

product=np.multiply(x,y)


In [43]:
print(product)

[[45  5 20]
 [40 20 35]
 [25 40 40]]


multiplying 2 matrices

In [44]:
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,3))
print(matrix_1)
print(matrix_2)

[[7 7 1]
 [5 2 1]
 [4 7 5]]
[[8 0 6]
 [9 0 8]
 [0 6 2]]


In [45]:
product=np.dot(matrix_1,matrix_2)
print(product)

[[119   6 100]
 [ 58   6  48]
 [ 95  30  90]]


In [46]:
product.shape

(3, 3)

In [47]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [50]:
product = np.dot(matrix_3, matrix_4)
print(product)


ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

element wise opeartion

In [51]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [52]:
print(matrix_3)


[[2 2 3]
 [2 2 4]
 [0 2 3]]


In [53]:
print(matrix_4)


[[2 2 1]
 [2 2 3]
 [0 3 3]]


In [54]:
product = np.multiply(matrix_3, matrix_4)


In [55]:
print(product)



[[ 4  4  3]
 [ 4  4 12]
 [ 0  6  9]]
